name: Build Project

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
  workflow_dispatch: {}
    

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'      
          distribution: 'graalvm-community' 
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Maven
        run: mvn --batch-mode --update-snapshots
